# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import NPAF_pb2 as NPAF__pb2


class RouteDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CollectRoutes = channel.unary_unary(
                '/RouteData/CollectRoutes',
                request_serializer=NPAF__pb2.RouteRequest.SerializeToString,
                response_deserializer=NPAF__pb2.DeviceRoutes.FromString,
                )


class RouteDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CollectRoutes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CollectRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectRoutes,
                    request_deserializer=NPAF__pb2.RouteRequest.FromString,
                    response_serializer=NPAF__pb2.DeviceRoutes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RouteData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RouteData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CollectRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RouteData/CollectRoutes',
            NPAF__pb2.RouteRequest.SerializeToString,
            NPAF__pb2.DeviceRoutes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
